package School;
public class Main {
    public static void main(String[]args){
        teacher t1 = new teacher("Марьян", "Сидорович", 295423515,"Физическая культура и здоровье");
        teacher t2 = new teacher("Станислав", "Карнило", 295423544,"Труд");
        teacher t3 = new teacher("Тереса", "Явсен", 295423554,"Математика");
        teacher t4 = new teacher("Галина", "Бальцевич", 295423544,"Физика");
        teacher t5 = new teacher("Виктория", "Сальдюн", 295423515,"Химия");
        teacher t6 = new teacher("Елена", "Светлович", 295423544,"Русский язык");
        teacher t7 = new teacher("Ирина", "Удавева", 295423515,"Белорусский язык");
        teacher t8 = new teacher("Павел", "Карнило", 295423544,"Русская литература");
        teacher t9 = new teacher("Марьян", "Кучугур", 295423515,"Белорусская литература");
        teacher t10 = new teacher("Бронислав", "Карнило", 295423544,"Биология");
        teacher t11 = new teacher("Марьян", "Салазар", 295423515,"Математика");
        teacher t12 = new teacher("Станислав", "Виклан", 295423544,"История");
        teacher t13 = new teacher("Гиркулес", "Владкокин", 295423544,"География");
        t1.text();
        System.out.println(t1.toString());
        System.out.println(t2.toString());
        System.out.println(t3.toString());
        System.out.println(t4.toString());
        System.out.println(t5.toString());
        System.out.println(t6.toString());
        System.out.println(t7.toString());
        System.out.println(t8.toString());
        System.out.println(t9.toString());
        System.out.println(t10.toString());
        System.out.println(t11.toString());
        System.out.println(t12.toString());
        System.out.println(t13.toString());
        leaders l1=new leaders("Дзанет", "Сидорович", 295423515,"Директор школы");
        leaders l2=new leaders("Виолетта", "Кринжак", 295423515,"Заместитель директора по воспитательной работе");
        leaders l3=new leaders("Кляус", "Кулик", 295423515,"Заместитель директора по учебной работе");
        leaders l4=new leaders("Клара", "Кнет", 295423515,"Заместитель директора по хозяйственной работе");
    l1.text();
    l1.initiliz();
    l2.initiliz();
    l3.initiliz();
    l4.initiliz();
    SchoolSubject s1=new SchoolSubject("Математика","Точная наука");
    SchoolSubject s2=new SchoolSubject("Физика","Точная наука");
        SchoolSubject s3=new SchoolSubject("Химия","Естественная наука");
        SchoolSubject s4=new SchoolSubject("Биология","Естественная наука");
        SchoolSubject s5=new SchoolSubject("История","Общественная наука");
        SchoolSubject s6=new SchoolSubject("География","Общественная наука");
        SchoolSubject s7=new SchoolSubject("Труд","-");
        SchoolSubject s8=new SchoolSubject("Физическая культура и здоровье","-");
        SchoolSubject s9=new SchoolSubject("Русский язык","-");
        SchoolSubject s10=new SchoolSubject("Белорусский язык","-");
        SchoolSubject s11=new SchoolSubject("Русская литература","-");
        SchoolSubject s12=new SchoolSubject("Белорусская литература","-");
        System.out.println(s1.toString());
        System.out.println(s2.toString());
        System.out.println(s3.toString());
        System.out.println(s4.toString());
        System.out.println(s5.toString());
        System.out.println(s6.toString());
        System.out.println(s7.toString());
        System.out.println(s8.toString());
        System.out.println(s9.toString());
        System.out.println(s10.toString());
        System.out.println(s11.toString());
        System.out.println(s12.toString());
        classrom cl1=new classrom(1,"A");
        classrom cl2=new classrom(1,"Б");
        classrom cl3=new classrom(2,"A");
        classrom cl4=new classrom(2,"Б");
        classrom cl5=new classrom(3,"A");
        classrom cl6=new classrom(3,"Б");
        classrom cl7=new classrom(4,"A");
        classrom cl8=new classrom(4,"Б");
        classrom cl9=new classrom(5,"A");
        classrom cl10=new classrom(5,"Б");
        classrom cl11=new classrom(6,"A");
        classrom cl12=new classrom(6,"Б");
        classrom cl13=new classrom(7,"A");
        classrom cl14=new classrom(7,"Б");
        classrom cl15=new classrom(8,"A");
        classrom cl16=new classrom(8,"Б");
        classrom cl17=new classrom(9,"A");
        classrom cl18=new classrom(9,"Б");
        classrom cl19=new classrom(10,"A");
        classrom cl20=new classrom(10,"Б");
        classrom cl21=new classrom(11,"A");
        classrom cl22=new classrom(11,"Б");
        cl1.initiliz();
        cl2.initiliz();
        cl3.initiliz();
        cl4.initiliz();
        cl5.initiliz();
        cl6.initiliz();
        cl7.initiliz();
        cl8.initiliz();
        cl9.initiliz();
        cl10.initiliz();
        cl11.initiliz();
        cl12.initiliz();
        cl13.initiliz();
        cl14.initiliz();
        cl15.initiliz();
        cl16.initiliz();
        cl17.initiliz();
        cl18.initiliz();
        cl19.initiliz();
        cl20.initiliz();
        cl21.initiliz();
        cl22.initiliz();
    }
}
